<!-- Main -->
<div class="wrapper style2">

    <article id="main" class="container special">
        <a href="#" class="image featured"><img src="images/714728_528.jpg" /></a>
        <header>
            <h2><a href="#"><?php echo Title; ?></a></h2>
            <span class="byline"><?php echo SubTitle; ?></span>
        </header>
        <p id="content_matn">
            interviewer :
            excellent. It's really an interesting story and I think that few people know and pay attention to the story behind this photo. By the way, you answered one of the questions in my mind, and the form and architecture of this building and the type of minarets that are built on it, I really wondered where it was inspired from? that you mentioned
            That Baqi is very important for all Muslims, not only Shiites, it can be said that it may be self-evident, of course, from another point of view, we see that the destruction of Baqi was not done by an external agent, but it was done from within this Ummah, but I wanted to see the importance of you. What do you know about the rest and in what angles and dimensions is this important? And what are the distinctions or differences of this historical cemetery or specifically now the shrine of Ahl al-Bayt (peace be upon them) with other similar works?
            Mr. Mojani:
            Allow me to share a name here in this perception that I reached. I also mentioned this name in the introduction of my book Taqareer al-Najd. Between 1381 and 1385, before I started this project, I was on a mission in France, and at that time in France, one of the issues we dealt with What we were facing was an attack on the cemeteries and graves of the Jews of France, where the extremist currents of the radicalism of France drew a broken cross on the doors and walls of these graves and places, and a point that was very interesting, in one of the cases where this attack took place, French President Mr. Chirac went and visited that cemetery and gave a speech there and said that this is an attack and we must respect the peace of our ancestors and the people who passed away! No matter what religion they have. It was an interesting point for us who worked at the agency. This forces the French president to take action. Fortunately, I went to Hajj that same year; In our caravan, which was Iranians abroad, Mr. Seyyed Ahmad Salahian was also present and together (because we saw him in the media in France, they talked and analyzed) we used to circumambulate, talk, and spend the night away. We had a dinner table and we discussed a lot.
            Among other things, I asked this question to Mr. Salamian, that because of his long stay in France, why the French government shows so much sensitivity to the invasion of graves. They gave me a description and then came to the example of Baqi. Regarding Baqi, he said that Baqi is the global memory of the Islamic world - at that time, Zarqawi's groups had just grown in Iraq and the current of Al-Qaeda in Iraq.
            It had started - they told me: When you take this memory, this emotion of human connection with its own past, it can be replaced by violence. After these personal studies that I have done and the events that I have encountered, I can say that his point and statement had a very correct basis and why Baqi' is different from other Islamic places and places. In my opinion, it is due to several features. First of all, Baqi is the common point of all religions and all Islamic beliefs; Because a grave does not belong to a sect or a religion or a specific nation. It is the only place after Mecca where pilgrims gather and regardless of their differences in terms of race, language, clothing, color, ethnicity and nationality, they go around the same place and perform their actions in one place.
            They practice a defined discipline, when they reach the rest, each lost person follows himself. The same extent that we Shias go to Bayt Al-Ahzan and go to the pilgrimage of our own imams, the Sunnis go there to look for their lost ones, and the Sufis also go to look for their lost ones. Different branches and layers of thought, ethnicity, language, nationalities and races, everyone has something lost there. Therefore, if we are performing actions in Makkah, there is the peak of our emotion that emerges, and this emotion is completely collective, and this emotion allows us to create a memory; The memory that is the unity of Islam and the integrity of the Islamic world, and when you take this memory and deny the possibility of expressing feelings and emotions, you will certainly take away the emotional connection point and the individual and human understanding of Muslims from each other. Maybe we have other places, for example; Martyrs of Uhud and Badr. These represent a specific event, but the rest are not like that at all. During the fourteen hundred years that have passed since Islam, Baqi has received one of the capitals, one of the Muslim figures every day and they have rested there and each of them has left a sign there, and there is a point that regardless of any orientation or reading We see that people can gather together and because they express their emotional feeling, it helps them to find a deeper understanding towards each other and this understanding is an intuitive understanding As I am crying, a Shazli Sufi is also crying there, a Hanafi jurist is crying, at a distance of several tens of meters from each other. As I am affected, it also mentions. Therefore, we are integrated in one point, and for this reason, I think that Baqi has a completely strategic value to create a collective sense in the feelings and emotions of the Islamic society, which very unintentionally creates that empathy, which is better in the sense of speaking the same language. brings.
            Interviewer:
            It is true. It is the same, and the explanation you provided makes me wonder even more, how can it be when all the Islamic religions and currents have such attachment and feelings towards others, and this has been the case throughout history, and the sign and evidence of it is all kinds of tombs that were built in the period Different historical buildings were built by different governments or different people there, then the wonder is how Wahhabism came to this conclusion to completely destroy here or basically how it dared to stand against all Islamic religions and currents. including theological currents, jurisprudential currents, mystical currents for which all these are relevant, and even the shrine of Ahl al-Bayt itself. Ahl al-Bayt is one of the axes of unity of the Islamic world. That is, the emphasis that the Qur'an and hadiths have on the love of Ahl al-Bayt, that is, the shrine of Ahl al-Bayt alone, seemed relevant to all Islamic currents. With these interpretations, why did Wahhabi do such a thing? And why did he bear such an exorbitant cost?
            Mr. Mojani:
            For the same reason that ISIS decided to destroy Islamic monuments and historical monuments in the territory of the Islamic State of Iraq and the Levant. For the same reason that every government that becomes the ruler tries to erase its past and every dynasty that comes, tries to change the related effects of the previous one. This is a very natural thing. Wahhabism is a reading of Islam. As the caliphate is a nostalgic image of an Islamic period. It does not represent a particular religion. Wahhabism does not represent Islam either. It is his own perception of Islam. If you pay attention to history, you will see that during the Seleucid period, there were many works in Iran, but when the Sasanians came, they destroyed them all. Why should they say that history begins with us, as ISIS wants to say that history begins with us, and as the Wahhabis want to say That is, returning to the predecessor is not only a return to the historical past, but in this return, this distance must also be eliminated, and in order to eliminate this distance, there is no history, no incident, no heritage, and no legacy in this distance. Therefore, these should be destroyed from the perspective they have for state building and governance, and this is something that appears in every current and movement or every policy that has an ideological perspective.
            Today we have to make a difference between the Saudi government and two hundred years ago when the first destruction took place. Today, the Saudi government says that I want to develop. Expand the infrastructure. As we are developing in many places, and the old texture is changing, but what happened that day; It was to destroy, remove and erase. When you remove and erase this, you can rule your own reading and format your own reading. But when there is a great symbol and a lasting legacy in front of you, this possibility is definitely not provided to you. Why ISIS destroys libraries; Because he didn't want this past to exist. At one point, he saw the end of the caliphate, and at one point in Mosul, Abu Bakr al-Baghdadi said, "I am Muhyiddin and the restorer of this caliphate." Therefore, what is in the middle must be destroyed in order to remain legitimate. For this reason, I want to say that the first motivation was with this view. Today, another government has come and found its own reasons.
            He says that I want to develop and settle. Behind it is the same thought, form and thought, but in execution it has a completely new format. We unfortunately when
            To lose our previous identity and our past, we lose our beliefs and when we lose our beliefs, we accept superstitions, we accept new rules. When we have a sign that we can follow, we reach the destination or origin that exists. But when you remove these signs, we wander in the Valley of Hirani, and this is the only thing that is a policy that gives a reading of Islam, either in the format of ISIS, or in the format of Al-Qaeda, or in the format of the Najdi Wahhabi Salafis. is showing. That's why it makes sense to me.
            Interviewer:
            You gave a very good explanation about the motivation of these and the history of such actions that you mentioned to the Sasanians. During the history of Islam in Iran, it has been one of these destructions and I think it is completely convincing.
            But did they have a support for implementing this, for example, did ISIS or someone like Abdul Aziz bin Saud and others not have a support outside the Islamic world that they could rely on to do such a task, which is really a huge task, a symbol of the greatness of the Ahl al-Bayt shrine, the shrine The wives of the Prophet, the children of the Prophet, the Companions, Malik Ibn Anas and the rest of the men who are buried there should be destroyed in two stages. What do you think about this?
            Mr. Mojani:
            It is very easy if we want to find an external reason for all the issues and problems that we get ourselves into. This unfortunately gives us a direction to be irresponsible. From accepting historical responsibility for the actions we took. For example, let's go back to two hundred years ago and say, for example, a certain English officer came and went in Dariyya, did this and gave this order, and this happened, or for example, the story of a narration that is told for Sheikh Muhammad bin Abdul Wahhab, which is a fabricated narration and He said he came, he did this! Leave these aside. Consider a fact about the German people today, a tragedy happened in World War II (which is our contemporary) in World War II, the Nazi army and the German government took an action to kill innocent people all over the geography. which the Germans had captured, he did. It didn't matter to them whether they killed a nation or a religion, it was horizontal development, it was a policy of racial superiority, and countless people of different nationalities and beliefs were unjustly killed there. What happened was that the German government accepted the responsibility for this massacre during these seventy years, and what happened was that the German government, due to the policy of racial superiority, proceeded to unjustly kill all human beings, regardless of their religion, Ethnicity, language, culture and geography they live in. Wherever it developed and conquered, this slaughter took different forms. It has been 70 years since the German nation and the German government accepted the responsibility for this massacre and they say that we were the ones who did it and we must pay for it and apologize. For what? To prevent the next thing from happening. Because the Second World War was because Germany did not accept the responsibility of the First World War and made a bigger mistake. If we could have pointed out the destruction of Baqi two hundred years ago to the vandals there, surely the following actions would not have been taken. But when we avoid responsibility and want to look at everything from an external point of view, we say that these are the representatives of the external flow! Not by chance.
            This incident happened from within this context, according to your words, a current has emerged within this Islamic society that continues today, killing people in Kabul, destroying in Samarra.
            exclaims The root of this is our own. We need to take responsibility for what happened and take responsibility to prevent it from happening again. But if we come and give an external reason for everything and say that this is an external reason, I am not saying that it is not an external reason, surely external complications or policies are also involved in any change, but the essence of that change, the engine of change and the origin of that change are influenced by It is an incorrect reading that we have in the whole Islamic world. If Salafis or Wahhabis present an incorrect recitation, if ISIS presents an incorrect recitation, Al-Qaeda presents, tomorrow the consequences will affect all of us. Now let's go and search and find an external root for it and say that it was not us and that these are not Muslims and so on. These are with Allahu Akbar.
            Interviewer :
            It is true. In this regard, a question arose for me, why was the destruction done in two stages? I mean, why wasn't it done at once? In the first stage, was there not the capacity to destroy completely and completely? I would be grateful if you could explain about these two stages.
            Mr. Mojani:
            Almost in terms of historical comparison, the first destruction coincided with the era of Fath Ali Shah Qajar, and the second destruction coincided with the beginning of the reign of Reza Shah Pahlavi. I say this, people who are in our country and follow things with our calendar, know what it is historically.
            What the documents say in the first attack, which is two hundred years ago, did not have the ability to completely physically destroy all the buildings that were built. Secondly, public sentiments have not accepted; It means there are resistances. Let us not forget that in the first event, the Muslims and the Sharif family of Makkah, who are Sadat Hashemites, had the power, the army, and the people who were under the support of the Ottoman government, and the Ottoman government was in conflict with these Najdi rebels who had attacked Medina. He defended Medina. Therefore, he did not allow the destruction more than they imagined or expected, and prevented the destruction, and then with the arrival of the Iranian army forces, after Ibrahim Pasha son of Khadeeb, Muhammad Ali Pasha from Egypt, this current and this first wave of Wahhabism during the era of Saud bin Abdulaziz and others was destroyed.
            In the second period, when the destruction was very extensive and covered a large area, it was remembered that it was the necessity of the conditions of the First World War. That ruling force and that power that was responsible for defending this land; That is, the Turkish governors of Baba Ali, because the Ottoman government was defeated in the first war, were returning to the Anatolian land and it was defenseless, and they did everything they could and completely destroyed it.
            The power of the nobles of Mecca was also weakened; Because the power of the nobles of Makkah depended on the power of the Supreme Leader and they took money, troops and forces from them. Therefore, they were there, and under the conditions of the First World War, which is comparable to the second destruction and the atmosphere of the second destruction of that era, we basically witness that no one could pay attention to the issue and there was no force to enter. While during the destruction of the first period, which is the era of Fath Ali Shah, the Iranian force was sent and entered Dariyah. That is, the Qajar government's Iranian army went to the center of Najd to suppress the Wahhabis who were attacking. There are documents of this. I have to say one thing about these two historical periods, there are two judgments among our researchers. Many believe that when an action was taken in the first period, it means that the Qajar period went and fought against the Wahhabis and sent an army. During the Pahlavi era and the beginning of Reza Shah's reign, why was this action not taken, and even the policy that we will mention later (the commission of Haramin Sharifin Modares) was not supported and welcomed by the government of Sardar Sepeh. We have to be very careful about this. That which shaped our behavior during the era of Feth Ali Shah; That is, for the first destruction and during Reza Shah's era for the second destruction, the impact was global and regional. In the first destruction, we decided to stand up for the defense of Medina when we were defeated in part of the Iran-Russia wars. The legitimacy of the Qajar government was questioned. Don't forget that during the Iran-Russia wars, Najaf scholars issued a fatwa
            It made the nation excited and it started, a part of this land is in the hands of the Russian infidels. In contrast to the defeat that was suffered and the capacity that was depleted due to the religious fatwas in the loss of the Caucasus regions, the action of Fath Ali Shah is a part of that characteristic. So, it was necessary to have an act here that can show itself as a supporter, that is, the government of Iran at that time. During the Pahlavi era, Reza Shah, the situation was completely different. Reza Shah came to power at a time when the consequences of the First World War had made this entire peripheral region of ours unstable and our peripheral region was formed in the process of a colonial world. The British force was in Iraq, the French force was in Shamat; In the same way, it was divided in Najd and the eastern lands. At that time, the government of Iran had a different policy and showed a different behavior. At that time, the policy of the Iranian government was to separate itself from these regions, which were completely filled with the occupation forces of the colonial forces, in order to preserve the independence of Iran.
            Therefore, the decision that was made at that time that we did not enter into this process and did not take any action, even in relation to the Haramin Sharifan Commission, which was a political act and lacked attention and carelessness, was partly due to the fact that we wanted to We separate ourselves. Reza Shah wanted to build a new Iran because he thought that if he did not do this, Iran would not separate and stabilize the borders. These twenty borders and the continuity of Iran with its surrounding environment make it possible for the complications and information that is around us to spread inside the country as well. Politics did it. Necessarily, none of them had a religious view, and when they were political rulers, they did not have a religious view of the issue, but their issue was first the geopolitics of Iran and based on the legitimacy of their ruling policy. Now, if religious excitement arose, something would happen and they would try to manage it and ride it.
            Interviewer :
            In my opinion, this early period had a great impact on this procedure. I think I read a book of yours about the Wahhabi attack on Karbala in 1258. In that situation, Naser al-Din Shah Qajari, even though the sovereignty of Atbat Alaiat was in the service of the Ottomans, he carried out extensive renovations in Karbala and Najaf and returned the shrine to its glorious state before the Wahhabi attack, and even better than that. It seems that these initial conditions had a great impact on this matter. Mention this as well. But apart from the Pahlavi government, you have mentioned the Haramin Sharifin Commission several times in your statements, I would appreciate it if you also mentioned the role of Martyr Modares in this regard and that it seems that he is central to this matter and his opposition to Reza Shah. , in that somehow failed
            It has been effective. I would appreciate it if you could explain about this.
            Mr. Mojani:
            Two separate issues. If you allow me to talk first about the Haramin Sharifin Committee, then I will return to the issue of the massacre in Karbala.
            When the second attack happened in parallel with the formation of the Pahlavi dynasty, the late Modares made a proposal that is very creative from an intellectual point of view. Of course, let's not be unfair, only the late Modares did not make this suggestion. A group of representatives of that legislative period of the National Assembly made this decision and proposed this article that we form a commission for the Holy Shrines and that this commission be multinational and different people are involved in it. The reason for this was that there was a wave among Indian Muslims, an association called Khodam Kaaba Association, which in India, they had the first movement, just like the incident of Salman Rushdie that started in India and Pakistan and the flame Ash ignited Then they started to correspond and telegraph. At In Iran, a number of intellectuals in the parliament, including Modares, proposed this commission and created a definition for this commission between the Islamic Majlis and started telegraphing the Majlis of Egypt, Turkey and India. Those telegrams were also answered and follow-up was done, the documents of which I found by chance in the archives of the Ministry of Foreign Affairs and I wrote an article about it. Of course, many years ago, twenty or so years ago, at the beginning of my career. What happened here? It was not just the beginning. We have to consider that at that time a conflict (not a personal conflict between Modares and Reza Shah) arose. At that time, we witnessed a structural confrontation in Iran's domestic politics. The Constituent Assembly is unable to carry out its duties
            and the governments affected by the conditions created by the world war and Iran's neutrality was violated and Iran's borders were violated, had a shaky state, and at that time there was a social need for a strong and capable government that would not be affected. , and they looked for this in the characters.
            The third coup of March shaped this process. The coup was against the basis of constitutionalism. Here, the confrontation between the government and the parliament is similar to what we have seen many times in contemporary history, this confrontation between the government and the parliament finally created a loss that prevented the parliament from being able to use the international capacity of the Haramin Sharifin Commission, which only Iran has raised its voice, and the government should use that policy to increase its diplomatic role. For this reason, I want to state very clearly that the internal differences between the structural institutions that make up the Iranian government at that time caused them to lose both diplomacy and the field. It is a pity that the Haramin Sharafin Commission could not establish its own diplomatic activity between the Islamic councils
            It is that we did not have any power as a part of the Islamic world to consolidate it or as much as our own share compared to what happened during the period of Fath Ali Shah, to prevent the destruction of the most important Shia Bekaa. This is very important today for us to understand how dependent these two factors are on each other, and they must be equally protected and careful, and if they are in conflict, the damage will be catastrophic for us. It insults our international capacity and takes away our geopolitical power capacity and turns us into an Iranian with a lifeless body.
            Interviewer:
            Answer the first question as well, but since we are nearing the end of our discussion, give us a brief summary so that we can get to the other questions.
            Mr. Mojani:
            That incident was not during Naser al-Din Shah's time, it was late Muhammad Shah Qajar, and part of it was related to a feeling that happened in Iran at that time. We had an unknown phenomenon. There was a fight in Karbala between Usulis and Akhbaris and it had escalated and the Iranian government had moved away from the territory where traditionally the majority of its population were Iranians. The incident of killing of Karbala by the Ottoman forces gave a heavy blow to the emotions and feelings of Iranians, and after that a phenomenon emerged that was very annoying during the era of Naser al-Din Shah and we still see it today, the movement of the Babis, the rise of the Bab. And the invitation of the Babis and the events that happened and continue. Here, Naseruddin Shah wisely considered a policy. Our relationship with Arab Iraq was severed. We had no authority there.
            But Nasir al-Din Shah used to say that I, as a Shia king, should go and visit Shia places and then settle and develop them. In this way, when he did this, he developed, expanded this space, promoted it, gave it a market, gave it an Iranian form, built palaces, and so on, then he made a document for all of them. in fact
            In one sentence and the end, "Iran's spiritual ownership over Arab Iraq was established in a situation where our material ownership was taken away from us."
            Interviewer :
            It is true and the truth is the same. Of course, until today, Naseruddin Shah is considered a lovable character in Atbat. I want to ask you this, what steps could have been taken in the last four decades regarding Baqi's and what were not done? What capacities were not used? And what paths could be taken to even revive Baqi, for example diplomacy, and basically how do you look at the future of this holy place? Do you see the prospect of reviving Baqi near or far? What is your opinion about this?
            Mr. Mojani:
            It has been 41 years since we came and discussed the unity between the Islamic world and as an Islamic revolution we prioritized Islamic values over our own values, principles, ethnic, cultural and inherent characteristics and protected them. We want to put
            In this call for unity, which was also the week of unity, the seminars and meetings that have been held for more than thirty consecutive years, in which one of them was the issue of Baqi? It means that we have moved to the same point that we said that all the Islamic world shares and where they have entrusted a part of their identity and past. Where did we want that during these years when we talked about unity and it has different topics, if you look at our unity and approximation conferences, you will see that each time is dedicated to the same topic. Did you never think like this or should we not have thought that Baqi was our connection point with the entire Islamic world. If we held a meeting regarding Baqi and the heritage that exists in Baqi, the personalities of Baqi, the tombs of Baqi, its traditions and the history of Baqi, what would we imagine? Were people not paying attention to me from Egypt and North Africa to Turkestan and the Caucasus and the Balkans from India and the eastern lands of Turkestan? because each of them has a part of themselves there; They have a scholar, they have a poet, they have a politician, they have a leader, they have a jurist. I think that, unfortunately, during these years, just as the Baqi's were oppressed during the centuries, our cultural and political understanding in the call of unity has shown neglect towards the value, importance and capital of the large baggage and this limited geographical area, which is the land of the Baqi's. It can have for us and connect us to all branches, beliefs, tendencies, sects and religions of Islam.
            Interviewer :
            God willing, some kind of special work, attention and sensitivity towards the Baqi issue will be formed in both Iran and Islamic countries. Thank you for this conversation we had about Baqi.
            Mr. Mojani:
            The only thing that comes to my mind is to pray that a deep and comprehensive knowledge of the grain by grain of the sands and particles of the soil of these holy places that is there will be created in the group of one billion Muslims in a fair way and that we will be able to Let's have the path of convergence and unity and stay away from bigotry, hatred and violence. The rest is the collective memory of each one of us. If we keep the rest, our customs and traditions will make sense in performing Hajj or performing Hajj. In relation to Baqi, we must always consider this, in front of Baqi there is a green dome that someone is watching and we must act in such a way that we do not offend the Prophet of Islam, whether in our own activities or on a path. that we want to march and the Prophet of Islam is not offended when we consider a look of mercy in relation to all human beings, as he was sent and inspired and spoke about that mission on the day of the conquest of Mecca.
        </p>
    </article>

</div>