<!-- Main -->
<div class="wrapper style2">

    <article id="main" class="container special">
        <a href="#" class="image featured"><img src="images/5401012.jpg" /></a>
        <header>
            <h2><a href="#"><?php echo Title; ?></a></h2>
            <span class="byline"><?php echo SubTitle; ?></span>
        </header>
        <p id="content_matn">
            My main problem was how to verify the authenticity of this photo? This project I was doing was for the World Assembly of Ahl al-Bayt. I reached my friends in the assembly and said that this is the picture. At first, they faced it with the same curious and ambiguous look, and then the evidence I showed them was very interesting. Then the discussion was, what can we use this image? I said that because the image is new and not very clear, especially because it was very interesting, when we zoom in on the image, in the circular or semi-circular inscription above the entrance of this blessed tomb, there is only one word in the corner. One word, and that word is Fatima, and in the travelogue of Ibn Maazah, the Hanbali jurist who traveled to Bukhara in 552 AH, he describes this place, saying: "This is the mosque or house of Fatima Zahra, peace be upon her." ». I told my friends that this image created two feelings for me; At first it was a surprise. The second was feeling affected. Surprised that this building with such a lofty and magnificent stature compared to the geography around it was above the graves of our imams, and impressed that we can't see anything there today, and this is a source of regret. So we have to promote this.
            Various forms were discussed, until we decided to publish this post in Germany and then distribute it to see what the reactions are. Alhamdulillah, the reactions were very good and maybe when it was distributed, it went to different places, it never had such an impact on me until one day when I was coming home from the Ministry of Foreign Affairs, I saw this image on a big billboard in Ferdowsi Square. and said that eight Shawwal is the anniversary of the destruction of Baqi. This is why I think the image is unique. Of course, later it helped that they searched more carefully in other places and other complementary images were found in the efforts of other researchers and enthusiasts.
            Another point is that the lady told me that this is a mansion in Turkestan. It was a surprise for me too! Why does this Turkish researcher or archivist have this idea? After paying attention, I want to share my feelings. It is also that the architecture of this building is very close to the architecture of, for example, the tomb of Shah Ismail Safavi in Bukhara in terms of its format, and on the other hand, to other tombs that we have in Central Asia, and my guess is that this building is somewhat different from the rest of the buildings. that there were other examples around, maybe it was modeled or built by Shiites or Ismailis who were present in that history and had invested in the construction of this building.
            Therefore, in terms of its architecture and characteristics, it is completely different and distinct from the format of our other Shia pyramids and their style, and it has its own special and unique characteristics, just as Najaf Ashraf has a distinctive pattern in its internal architectural format. It has other properties.
        </p>
    </article>

</div>